# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='entity',
        ),
        migrations.AddField(
            model_name='query',
            name='engines',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='entities',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
